"""Haltewerte der „Soll unklar"-Sichten beider Abnahme-Matrizen (HA-Bauform E0, eingefroren 05.10.2026).

Eine „Soll unklar"-Sicht wird gemessen und gezeigt, aber nicht bewertet — die Regel legt ihr Soll nicht fest
(``test_pv_achse_matrix.SOLL_UNKLAR``; ``test_achsen_matrix._soll_unklar``: ``SOLL_UNKLAR_MENGE``, die
S3-Vor-Regel ``_U_SA_VOR`` und die Klima-Arbeitszahl). Damit der Umbau auf die HA-Bauform
(``~/.claude/plans/bauplan-ha-bauform-s1-s2.md`` §7, letzte Zeile) sie nicht **still** ändert, steht hier je
Sicht der gemessene Wert gegen HEAD ``263c9d12``; ``test_soll_unklar_haltewert`` in beiden Matrix-Dateien prüft
„gemessen == festgehalten" (``None`` = keine Angabe; Zahl gleich bis 1e-6) und, dass jede „Soll unklar"-Sicht
genau einen Haltewert hat.

**Kein Soll.** Ein Haltewert sagt nicht, dass der Wert richtig ist — die Fachentscheide folgen getrennt. Wer einen
Wert absichtlich ändert (Fachentscheid oder Umbau mit benanntem Zielwert), ändert ihn hier mit Verweis; fällt eine
Sicht aus „Soll unklar" heraus, fällt ihr Haltewert mit.

Erzeugt aus der Messung beider Matrizen (Berlin; ``TZ=UTC`` gemessen identisch), Bericht
``~/.claude/plans/opus-berichte/HA-BAUFORM-E0.md`` Punkt 4.
"""

from __future__ import annotations

from typing import Optional

#: ``(Form, Weg, Invariante, Sicht) → gemessener Wert`` — PV-Matrix, 116 Sichten.
PV_HALTEWERTE: dict[tuple[str, str, str, str], Optional[float]] = {
    ('F01', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F01', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F01', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F01', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F02', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F02', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F02', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F02', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F03', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F03', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F03', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F03', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F04', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F04', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F04', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F04', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F05', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F05', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F05', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F05', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F06', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F06', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F06', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F06', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F07', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F07', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F07', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F07', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F08a', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F08a', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F08a', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F08a', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F08b', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F08b', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F08b', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F08b', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F09a-G', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F09a-G', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F09a-G', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F09a-G', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F09a-oG', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F09a-oG', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F09a-oG', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F09a-oG', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F09b-G', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F09b-G', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F09b-G', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F09b-G', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F09b-oG', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F09b-oG', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F09b-oG', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F09b-oG', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F09c-G', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F09c-G', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F09c-G', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F09c-G', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F09c-oG', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F09c-oG', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F09c-oG', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F09c-oG', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F10', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F10', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F10', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F10', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F11', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F11', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F11', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F11', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F12', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F12', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F12', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F12', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F13a', 'S1', 'I5', 'geld:community:co2'): 171.0,
    ('F13a', 'S1', 'I5', 'geld:ha_export:co2'): 171.0,
    ('F13a', 'S1', 'I5', 'geld:ha_export:ev_ersparnis'): 135.0,
    ('F13a', 'S1', 'I5', 'geld:monat:ev_ersparnis'): 135.0,
    ('F13a', 'S1', 'I5', 'geld:pdf:ev_ersparnis'): 135.0,
    ('F13a', 'S1', 'I5', 'geld:tabelle:ev_ersparnis'): 135.0,
    ('F13a', 'S1', 'I5', 'geld:uebersicht:co2'): 171.0,
    ('F13a', 'S1', 'I5', 'geld:uebersicht:ev_ersparnis'): 135.0,
    ('F13a', 'S2', 'I5', 'geld:community:co2'): 171.0,
    ('F13a', 'S2', 'I5', 'geld:ha_export:co2'): 171.0,
    ('F13a', 'S2', 'I5', 'geld:ha_export:ev_ersparnis'): 135.0,
    ('F13a', 'S2', 'I5', 'geld:monat:ev_ersparnis'): 135.0,
    ('F13a', 'S2', 'I5', 'geld:pdf:ev_ersparnis'): 135.0,
    ('F13a', 'S2', 'I5', 'geld:tabelle:ev_ersparnis'): 135.0,
    ('F13a', 'S2', 'I5', 'geld:uebersicht:co2'): 171.0,
    ('F13a', 'S2', 'I5', 'geld:uebersicht:ev_ersparnis'): 135.0,
    ('F13a', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F13a', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F13a', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F13a', 'S3', 'I5', 'geld:community:co2'): 171.0,
    ('F13a', 'S3', 'I5', 'geld:ha_export:co2'): 171.0,
    ('F13a', 'S3', 'I5', 'geld:ha_export:ev_ersparnis'): 135.0,
    ('F13a', 'S3', 'I5', 'geld:monat:ev_ersparnis'): 135.0,
    ('F13a', 'S3', 'I5', 'geld:pdf:ev_ersparnis'): 135.0,
    ('F13a', 'S3', 'I5', 'geld:tabelle:ev_ersparnis'): 135.0,
    ('F13a', 'S3', 'I5', 'geld:uebersicht:co2'): 171.0,
    ('F13a', 'S3', 'I5', 'geld:uebersicht:ev_ersparnis'): 135.0,
    ('F13a', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F13b', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F13b', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F13b', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F13b', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F14', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F14', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F14', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F14', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F15', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F15', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F15', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F15', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F16', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F16', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F16', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F16', 'S3', 'I6', 'vor:cockpit_monat'): None,
}

#: ``(Form, Größe, Weg, Invariante, Sicht) → gemessener Wert`` — Achsen-Matrix, 389 Sichten.
ACHSEN_HALTEWERTE: dict[tuple[str, str, str, str, str], Optional[float]] = {
    ('M01', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M01', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M01', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M01', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M01', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M01', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M01', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M01', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M02', 'emob', 'S3', 'I2', 'heim_netz:cockpit_monat:vor=nach'): 0.0,
    ('M02', 'emob', 'S3', 'I2', 'heim_pv:cockpit_monat:vor=nach'): 0.0,
    ('M02', 'emob', 'S3', 'I2', 'heimladung:cockpit_monat:vor=nach'): None,
    ('M02', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M02', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M02', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M02', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M02', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M02', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M02', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M02', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M02', 'speicher', 'S3', 'I2', 'entladung:cockpit_monat:vor=nach'): None,
    ('M02', 'speicher', 'S3', 'I2', 'ladung:cockpit_monat:vor=nach'): None,
    ('M03', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M03', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M03', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M03', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M03', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M03', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M03', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M03', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M04', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M04', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M04', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M04', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M04', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M04', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M04', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M04', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M04', 'speicher', 'S3', 'I2', 'entladung:cockpit_monat:vor=nach'): None,
    ('M04', 'speicher', 'S3', 'I2', 'ladung:cockpit_monat:vor=nach'): None,
    ('M04', 'speicher', 'S3', 'I2', 'netzladung:cockpit_monat:vor=nach'): None,
    ('M05', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M05', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M05', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M05', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M05', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M05', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M05', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M05', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M05', 'wp', 'HA', 'I1', 'heizung:cockpit_jahr'): None,
    ('M05', 'wp', 'HA', 'I1', 'heizung:fakten_tw'): 0.0,
    ('M05', 'wp', 'HA', 'I1', 'heizung:jahr_verlauf'): None,
    ('M05', 'wp', 'HA', 'I1', 'modus_heizen:cockpit_jahr'): None,
    ('M05', 'wp', 'HA', 'I1', 'modus_heizen:fakten_tw'): 0.0,
    ('M05', 'wp', 'HA', 'I1', 'modus_warmwasser:cockpit_jahr'): None,
    ('M05', 'wp', 'HA', 'I1', 'modus_warmwasser:fakten_tw'): 0.0,
    ('M05', 'wp', 'HA', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M05', 'wp', 'HA', 'I1', 'warmwasser:fakten_tw'): 0.0,
    ('M05', 'wp', 'HA', 'I1', 'warmwasser:jahr_verlauf'): None,
    ('M05', 'wp', 'HA', 'I3', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'HA', 'I3', 'heizung:fakten_tw'): 0.0,
    ('M05', 'wp', 'HA', 'I3', 'modus_heizen:cockpit_monat'): None,
    ('M05', 'wp', 'HA', 'I3', 'modus_heizen:fakten_tw'): 0.0,
    ('M05', 'wp', 'HA', 'I3', 'modus_warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'HA', 'I3', 'modus_warmwasser:fakten_tw'): 0.0,
    ('M05', 'wp', 'HA', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'HA', 'I3', 'warmwasser:fakten_tw'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'heizung:cockpit_jahr'): None,
    ('M05', 'wp', 'S1', 'I1', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'S1', 'I1', 'heizung:community'): 648.0,
    ('M05', 'wp', 'S1', 'I1', 'heizung:pdf_kopf'): None,
    ('M05', 'wp', 'S1', 'I1', 'heizung:tabelle'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'heizung:uebersicht'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'heizung:zeitreihe'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'modus_heizen:cockpit_jahr'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'modus_heizen:cockpit_monat'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'modus_heizen:uebersicht'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'modus_heizen:zeitreihe'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'modus_warmwasser:cockpit_jahr'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'modus_warmwasser:cockpit_monat'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'modus_warmwasser:uebersicht'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'modus_warmwasser:zeitreihe'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M05', 'wp', 'S1', 'I1', 'warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'S1', 'I1', 'warmwasser:community'): None,
    ('M05', 'wp', 'S1', 'I1', 'warmwasser:pdf_kopf'): None,
    ('M05', 'wp', 'S1', 'I1', 'warmwasser:tabelle'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'warmwasser:uebersicht'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'warmwasser:zeitreihe'): 0.0,
    ('M05', 'wp', 'S1', 'I2', 'heizung:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S1', 'I2', 'heizung:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S1', 'I2', 'heizung:jahr_verlauf:vor=nach'): None,
    ('M05', 'wp', 'S1', 'I2', 'modus_heizen:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S1', 'I2', 'modus_heizen:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S1', 'I2', 'modus_warmwasser:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S1', 'I2', 'modus_warmwasser:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S1', 'I2', 'warmwasser:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S1', 'I2', 'warmwasser:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S1', 'I2', 'warmwasser:jahr_verlauf:vor=nach'): None,
    ('M05', 'wp', 'S1', 'I3', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'S1', 'I3', 'heizung:fakten'): 0.0,
    ('M05', 'wp', 'S1', 'I3', 'modus_heizen:cockpit_monat'): 0.0,
    ('M05', 'wp', 'S1', 'I3', 'modus_heizen:fakten'): 0.0,
    ('M05', 'wp', 'S1', 'I3', 'modus_warmwasser:cockpit_monat'): 0.0,
    ('M05', 'wp', 'S1', 'I3', 'modus_warmwasser:fakten'): 0.0,
    ('M05', 'wp', 'S1', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'S1', 'I3', 'warmwasser:fakten'): 0.0,
    ('M05', 'wp', 'S1', 'I6', 'heizung:cockpit_jahr'): None,
    ('M05', 'wp', 'S1', 'I6', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'S1', 'I6', 'heizung:community'): 648.0,
    ('M05', 'wp', 'S1', 'I6', 'heizung:fakten'): 0.0,
    ('M05', 'wp', 'S1', 'I6', 'heizung:pdf_kopf'): None,
    ('M05', 'wp', 'S1', 'I6', 'heizung:tabelle'): 0.0,
    ('M05', 'wp', 'S1', 'I6', 'heizung:uebersicht'): 0.0,
    ('M05', 'wp', 'S1', 'I6', 'heizung:zeitreihe'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'heizung:cockpit_jahr'): None,
    ('M05', 'wp', 'S2', 'I1', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'S2', 'I1', 'heizung:community'): 648.0,
    ('M05', 'wp', 'S2', 'I1', 'heizung:pdf_kopf'): None,
    ('M05', 'wp', 'S2', 'I1', 'heizung:tabelle'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'heizung:uebersicht'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'heizung:zeitreihe'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'modus_heizen:cockpit_jahr'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'modus_heizen:cockpit_monat'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'modus_heizen:uebersicht'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'modus_heizen:zeitreihe'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'modus_warmwasser:cockpit_jahr'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'modus_warmwasser:cockpit_monat'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'modus_warmwasser:uebersicht'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'modus_warmwasser:zeitreihe'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M05', 'wp', 'S2', 'I1', 'warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'S2', 'I1', 'warmwasser:community'): None,
    ('M05', 'wp', 'S2', 'I1', 'warmwasser:pdf_kopf'): None,
    ('M05', 'wp', 'S2', 'I1', 'warmwasser:tabelle'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'warmwasser:uebersicht'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'warmwasser:zeitreihe'): 0.0,
    ('M05', 'wp', 'S2', 'I2', 'heizung:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S2', 'I2', 'heizung:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S2', 'I2', 'heizung:jahr_verlauf:vor=nach'): None,
    ('M05', 'wp', 'S2', 'I2', 'modus_heizen:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S2', 'I2', 'modus_heizen:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S2', 'I2', 'modus_warmwasser:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S2', 'I2', 'modus_warmwasser:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S2', 'I2', 'warmwasser:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S2', 'I2', 'warmwasser:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S2', 'I2', 'warmwasser:jahr_verlauf:vor=nach'): None,
    ('M05', 'wp', 'S2', 'I3', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'S2', 'I3', 'heizung:fakten'): 0.0,
    ('M05', 'wp', 'S2', 'I3', 'modus_heizen:cockpit_monat'): 0.0,
    ('M05', 'wp', 'S2', 'I3', 'modus_heizen:fakten'): 0.0,
    ('M05', 'wp', 'S2', 'I3', 'modus_warmwasser:cockpit_monat'): 0.0,
    ('M05', 'wp', 'S2', 'I3', 'modus_warmwasser:fakten'): 0.0,
    ('M05', 'wp', 'S2', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'S2', 'I3', 'warmwasser:fakten'): 0.0,
    ('M05', 'wp', 'S2', 'I6', 'heizung:cockpit_jahr'): None,
    ('M05', 'wp', 'S2', 'I6', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'S2', 'I6', 'heizung:community'): 648.0,
    ('M05', 'wp', 'S2', 'I6', 'heizung:fakten'): 0.0,
    ('M05', 'wp', 'S2', 'I6', 'heizung:pdf_kopf'): None,
    ('M05', 'wp', 'S2', 'I6', 'heizung:tabelle'): 0.0,
    ('M05', 'wp', 'S2', 'I6', 'heizung:uebersicht'): 0.0,
    ('M05', 'wp', 'S2', 'I6', 'heizung:zeitreihe'): 0.0,
    ('M05', 'wp', 'S3', 'I1', 'heizung:cockpit_jahr'): None,
    ('M05', 'wp', 'S3', 'I1', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'S3', 'I1', 'heizung:community'): 648.0,
    ('M05', 'wp', 'S3', 'I1', 'heizung:pdf_kopf'): None,
    ('M05', 'wp', 'S3', 'I1', 'heizung:tabelle'): 0.0,
    ('M05', 'wp', 'S3', 'I1', 'heizung:uebersicht'): 0.0,
    ('M05', 'wp', 'S3', 'I1', 'heizung:zeitreihe'): 0.0,
    ('M05', 'wp', 'S3', 'I1', 'modus_heizen:cockpit_jahr'): None,
    ('M05', 'wp', 'S3', 'I1', 'modus_heizen:cockpit_monat'): None,
    ('M05', 'wp', 'S3', 'I1', 'modus_heizen:uebersicht'): None,
    ('M05', 'wp', 'S3', 'I1', 'modus_heizen:zeitreihe'): None,
    ('M05', 'wp', 'S3', 'I1', 'modus_warmwasser:cockpit_jahr'): None,
    ('M05', 'wp', 'S3', 'I1', 'modus_warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'S3', 'I1', 'modus_warmwasser:uebersicht'): None,
    ('M05', 'wp', 'S3', 'I1', 'modus_warmwasser:zeitreihe'): None,
    ('M05', 'wp', 'S3', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M05', 'wp', 'S3', 'I1', 'warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'S3', 'I1', 'warmwasser:community'): None,
    ('M05', 'wp', 'S3', 'I1', 'warmwasser:pdf_kopf'): None,
    ('M05', 'wp', 'S3', 'I1', 'warmwasser:tabelle'): 0.0,
    ('M05', 'wp', 'S3', 'I1', 'warmwasser:uebersicht'): 0.0,
    ('M05', 'wp', 'S3', 'I1', 'warmwasser:zeitreihe'): 0.0,
    ('M05', 'wp', 'S3', 'I2', 'heizung:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S3', 'I2', 'heizung:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S3', 'I2', 'heizung:jahr_verlauf:vor=nach'): None,
    ('M05', 'wp', 'S3', 'I2', 'modus_heizen:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S3', 'I2', 'modus_heizen:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S3', 'I2', 'modus_warmwasser:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S3', 'I2', 'modus_warmwasser:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S3', 'I2', 'strom:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S3', 'I2', 'waerme:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S3', 'I2', 'warmwasser:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S3', 'I2', 'warmwasser:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S3', 'I2', 'warmwasser:jahr_verlauf:vor=nach'): None,
    ('M05', 'wp', 'S3', 'I3', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'S3', 'I3', 'heizung:fakten'): 0.0,
    ('M05', 'wp', 'S3', 'I3', 'modus_heizen:cockpit_monat'): None,
    ('M05', 'wp', 'S3', 'I3', 'modus_heizen:fakten'): 0.0,
    ('M05', 'wp', 'S3', 'I3', 'modus_warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'S3', 'I3', 'modus_warmwasser:fakten'): 0.0,
    ('M05', 'wp', 'S3', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'S3', 'I3', 'warmwasser:fakten'): 0.0,
    ('M05', 'wp', 'S3', 'I6', 'heizung:cockpit_jahr'): None,
    ('M05', 'wp', 'S3', 'I6', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'S3', 'I6', 'heizung:community'): 648.0,
    ('M05', 'wp', 'S3', 'I6', 'heizung:fakten'): 0.0,
    ('M05', 'wp', 'S3', 'I6', 'heizung:pdf_kopf'): None,
    ('M05', 'wp', 'S3', 'I6', 'heizung:tabelle'): 0.0,
    ('M05', 'wp', 'S3', 'I6', 'heizung:uebersicht'): 0.0,
    ('M05', 'wp', 'S3', 'I6', 'heizung:zeitreihe'): 0.0,
    ('M05', 'wp', 'SA', 'I1', 'heizung:cockpit_jahr'): None,
    ('M05', 'wp', 'SA', 'I1', 'heizung:fakten_tw'): 0.0,
    ('M05', 'wp', 'SA', 'I1', 'heizung:jahr_verlauf'): None,
    ('M05', 'wp', 'SA', 'I1', 'modus_heizen:cockpit_jahr'): None,
    ('M05', 'wp', 'SA', 'I1', 'modus_heizen:fakten_tw'): 0.0,
    ('M05', 'wp', 'SA', 'I1', 'modus_warmwasser:cockpit_jahr'): None,
    ('M05', 'wp', 'SA', 'I1', 'modus_warmwasser:fakten_tw'): 0.0,
    ('M05', 'wp', 'SA', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M05', 'wp', 'SA', 'I1', 'warmwasser:fakten_tw'): 0.0,
    ('M05', 'wp', 'SA', 'I1', 'warmwasser:jahr_verlauf'): None,
    ('M05', 'wp', 'SA', 'I3', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'SA', 'I3', 'heizung:fakten_tw'): 0.0,
    ('M05', 'wp', 'SA', 'I3', 'modus_heizen:cockpit_monat'): None,
    ('M05', 'wp', 'SA', 'I3', 'modus_heizen:fakten_tw'): 0.0,
    ('M05', 'wp', 'SA', 'I3', 'modus_warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'SA', 'I3', 'modus_warmwasser:fakten_tw'): 0.0,
    ('M05', 'wp', 'SA', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'SA', 'I3', 'warmwasser:fakten_tw'): 0.0,
    ('M06', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M06', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M06', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M06', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M06', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M06', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M06', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M06', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M06', 'wp', 'HA', 'I5', 'cockpit_monat:jaz:Klima'): None,
    ('M06', 'wp', 'S1', 'I5', 'cockpit_monat:jaz:Klima'): 3.0,
    ('M06', 'wp', 'S2', 'I5', 'cockpit_monat:jaz:Klima'): 3.0,
    ('M06', 'wp', 'S3', 'I2', 'heizung:cockpit_monat:vor=nach'): None,
    ('M06', 'wp', 'S3', 'I2', 'kaelte:cockpit_monat:vor=nach'): None,
    ('M06', 'wp', 'S3', 'I2', 'modus_heizen:cockpit_monat:vor=nach'): None,
    ('M06', 'wp', 'S3', 'I2', 'modus_kuehlen:cockpit_monat:vor=nach'): None,
    ('M06', 'wp', 'S3', 'I2', 'strom:cockpit_monat:vor=nach'): None,
    ('M06', 'wp', 'S3', 'I2', 'strom_heizen:cockpit_monat:vor=nach'): None,
    ('M06', 'wp', 'S3', 'I2', 'strom_warmwasser:cockpit_monat:vor=nach'): None,
    ('M06', 'wp', 'S3', 'I2', 'waerme:cockpit_monat:vor=nach'): None,
    ('M06', 'wp', 'S3', 'I2', 'warmwasser:cockpit_monat:vor=nach'): None,
    ('M06', 'wp', 'S3', 'I5', 'cockpit_monat:jaz:Klima'): 3.0,
    ('M06', 'wp', 'SA', 'I5', 'cockpit_monat:jaz:Klima'): None,
    ('M07', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M07', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M07', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M07', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M07', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M07', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M07', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M07', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M07', 'sonstiges', 'S3', 'I2', 'verbrauch:cockpit_monat:vor=nach'): None,
    ('M07', 'wp', 'HA', 'I1', 'heizung:cockpit_jahr'): None,
    ('M07', 'wp', 'HA', 'I1', 'heizung:fakten_tw'): 0.0,
    ('M07', 'wp', 'HA', 'I1', 'heizung:jahr_verlauf'): None,
    ('M07', 'wp', 'HA', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M07', 'wp', 'HA', 'I1', 'warmwasser:fakten_tw'): 0.0,
    ('M07', 'wp', 'HA', 'I1', 'warmwasser:jahr_verlauf'): None,
    ('M07', 'wp', 'HA', 'I3', 'heizung:cockpit_monat'): None,
    ('M07', 'wp', 'HA', 'I3', 'heizung:fakten_tw'): 0.0,
    ('M07', 'wp', 'HA', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M07', 'wp', 'HA', 'I3', 'warmwasser:fakten_tw'): 0.0,
    ('M07', 'wp', 'S1', 'I1', 'heizung:cockpit_jahr'): None,
    ('M07', 'wp', 'S1', 'I1', 'heizung:cockpit_monat'): None,
    ('M07', 'wp', 'S1', 'I1', 'heizung:community'): None,
    ('M07', 'wp', 'S1', 'I1', 'heizung:pdf_kopf'): None,
    ('M07', 'wp', 'S1', 'I1', 'heizung:tabelle'): 0.0,
    ('M07', 'wp', 'S1', 'I1', 'heizung:uebersicht'): 0.0,
    ('M07', 'wp', 'S1', 'I1', 'heizung:zeitreihe'): 0.0,
    ('M07', 'wp', 'S1', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M07', 'wp', 'S1', 'I1', 'warmwasser:cockpit_monat'): None,
    ('M07', 'wp', 'S1', 'I1', 'warmwasser:community'): None,
    ('M07', 'wp', 'S1', 'I1', 'warmwasser:pdf_kopf'): None,
    ('M07', 'wp', 'S1', 'I1', 'warmwasser:tabelle'): 0.0,
    ('M07', 'wp', 'S1', 'I1', 'warmwasser:uebersicht'): 0.0,
    ('M07', 'wp', 'S1', 'I1', 'warmwasser:zeitreihe'): 0.0,
    ('M07', 'wp', 'S1', 'I2', 'heizung:cockpit_monat:vor=nach'): None,
    ('M07', 'wp', 'S1', 'I2', 'heizung:fakten:tageswert=gespeichert'): 0.0,
    ('M07', 'wp', 'S1', 'I2', 'heizung:jahr_verlauf:vor=nach'): None,
    ('M07', 'wp', 'S1', 'I2', 'warmwasser:cockpit_monat:vor=nach'): None,
    ('M07', 'wp', 'S1', 'I2', 'warmwasser:fakten:tageswert=gespeichert'): 0.0,
    ('M07', 'wp', 'S1', 'I2', 'warmwasser:jahr_verlauf:vor=nach'): None,
    ('M07', 'wp', 'S1', 'I3', 'heizung:cockpit_monat'): None,
    ('M07', 'wp', 'S1', 'I3', 'heizung:fakten'): 0.0,
    ('M07', 'wp', 'S1', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M07', 'wp', 'S1', 'I3', 'warmwasser:fakten'): 0.0,
    ('M07', 'wp', 'S2', 'I1', 'heizung:cockpit_jahr'): None,
    ('M07', 'wp', 'S2', 'I1', 'heizung:cockpit_monat'): None,
    ('M07', 'wp', 'S2', 'I1', 'heizung:community'): None,
    ('M07', 'wp', 'S2', 'I1', 'heizung:pdf_kopf'): None,
    ('M07', 'wp', 'S2', 'I1', 'heizung:tabelle'): 0.0,
    ('M07', 'wp', 'S2', 'I1', 'heizung:uebersicht'): 0.0,
    ('M07', 'wp', 'S2', 'I1', 'heizung:zeitreihe'): 0.0,
    ('M07', 'wp', 'S2', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M07', 'wp', 'S2', 'I1', 'warmwasser:cockpit_monat'): None,
    ('M07', 'wp', 'S2', 'I1', 'warmwasser:community'): None,
    ('M07', 'wp', 'S2', 'I1', 'warmwasser:pdf_kopf'): None,
    ('M07', 'wp', 'S2', 'I1', 'warmwasser:tabelle'): 0.0,
    ('M07', 'wp', 'S2', 'I1', 'warmwasser:uebersicht'): 0.0,
    ('M07', 'wp', 'S2', 'I1', 'warmwasser:zeitreihe'): 0.0,
    ('M07', 'wp', 'S2', 'I2', 'heizung:cockpit_monat:vor=nach'): None,
    ('M07', 'wp', 'S2', 'I2', 'heizung:fakten:tageswert=gespeichert'): 0.0,
    ('M07', 'wp', 'S2', 'I2', 'heizung:jahr_verlauf:vor=nach'): None,
    ('M07', 'wp', 'S2', 'I2', 'warmwasser:cockpit_monat:vor=nach'): None,
    ('M07', 'wp', 'S2', 'I2', 'warmwasser:fakten:tageswert=gespeichert'): 0.0,
    ('M07', 'wp', 'S2', 'I2', 'warmwasser:jahr_verlauf:vor=nach'): None,
    ('M07', 'wp', 'S2', 'I3', 'heizung:cockpit_monat'): None,
    ('M07', 'wp', 'S2', 'I3', 'heizung:fakten'): 0.0,
    ('M07', 'wp', 'S2', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M07', 'wp', 'S2', 'I3', 'warmwasser:fakten'): 0.0,
    ('M07', 'wp', 'S3', 'I1', 'heizung:cockpit_jahr'): None,
    ('M07', 'wp', 'S3', 'I1', 'heizung:cockpit_monat'): None,
    ('M07', 'wp', 'S3', 'I1', 'heizung:community'): None,
    ('M07', 'wp', 'S3', 'I1', 'heizung:pdf_kopf'): None,
    ('M07', 'wp', 'S3', 'I1', 'heizung:tabelle'): 0.0,
    ('M07', 'wp', 'S3', 'I1', 'heizung:uebersicht'): 0.0,
    ('M07', 'wp', 'S3', 'I1', 'heizung:zeitreihe'): 0.0,
    ('M07', 'wp', 'S3', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M07', 'wp', 'S3', 'I1', 'warmwasser:cockpit_monat'): None,
    ('M07', 'wp', 'S3', 'I1', 'warmwasser:community'): None,
    ('M07', 'wp', 'S3', 'I1', 'warmwasser:pdf_kopf'): None,
    ('M07', 'wp', 'S3', 'I1', 'warmwasser:tabelle'): 0.0,
    ('M07', 'wp', 'S3', 'I1', 'warmwasser:uebersicht'): 0.0,
    ('M07', 'wp', 'S3', 'I1', 'warmwasser:zeitreihe'): 0.0,
    ('M07', 'wp', 'S3', 'I2', 'heizung:cockpit_monat:vor=nach'): None,
    ('M07', 'wp', 'S3', 'I2', 'heizung:fakten:tageswert=gespeichert'): 0.0,
    ('M07', 'wp', 'S3', 'I2', 'heizung:jahr_verlauf:vor=nach'): None,
    ('M07', 'wp', 'S3', 'I2', 'strom:cockpit_monat:vor=nach'): None,
    ('M07', 'wp', 'S3', 'I2', 'waerme:cockpit_monat:vor=nach'): None,
    ('M07', 'wp', 'S3', 'I2', 'warmwasser:cockpit_monat:vor=nach'): None,
    ('M07', 'wp', 'S3', 'I2', 'warmwasser:fakten:tageswert=gespeichert'): 0.0,
    ('M07', 'wp', 'S3', 'I2', 'warmwasser:jahr_verlauf:vor=nach'): None,
    ('M07', 'wp', 'S3', 'I3', 'heizung:cockpit_monat'): None,
    ('M07', 'wp', 'S3', 'I3', 'heizung:fakten'): 0.0,
    ('M07', 'wp', 'S3', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M07', 'wp', 'S3', 'I3', 'warmwasser:fakten'): 0.0,
    ('M07', 'wp', 'SA', 'I1', 'heizung:cockpit_jahr'): None,
    ('M07', 'wp', 'SA', 'I1', 'heizung:fakten_tw'): 0.0,
    ('M07', 'wp', 'SA', 'I1', 'heizung:jahr_verlauf'): None,
    ('M07', 'wp', 'SA', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M07', 'wp', 'SA', 'I1', 'warmwasser:fakten_tw'): 0.0,
    ('M07', 'wp', 'SA', 'I1', 'warmwasser:jahr_verlauf'): None,
    ('M07', 'wp', 'SA', 'I3', 'heizung:cockpit_monat'): None,
    ('M07', 'wp', 'SA', 'I3', 'heizung:fakten_tw'): 0.0,
    ('M07', 'wp', 'SA', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M07', 'wp', 'SA', 'I3', 'warmwasser:fakten_tw'): 0.0,
    ('M08', 'emob', 'S3', 'I2', 'heim_netz:cockpit_monat:vor=nach'): 0.0,
    ('M08', 'emob', 'S3', 'I2', 'heim_pv:cockpit_monat:vor=nach'): 90.0,
    ('M08', 'emob', 'S3', 'I2', 'heimladung:cockpit_monat:vor=nach'): None,
    ('M08', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M08', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M08', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M08', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M08', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M08', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M08', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M08', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M09', 'emob', 'S3', 'I2', 'heim_netz:cockpit_monat:vor=nach'): 0.0,
    ('M09', 'emob', 'S3', 'I2', 'heim_pv:cockpit_monat:vor=nach'): 0.0,
    ('M09', 'emob', 'S3', 'I2', 'heimladung:cockpit_monat:vor=nach'): None,
    ('M09', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M09', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M09', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M09', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M09', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M09', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M09', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M09', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M10', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M10', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M10', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M10', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M10', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M10', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M10', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M10', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M10', 'sonstiges', 'S3', 'I2', 'erzeugung:cockpit_monat:vor=nach'): None,
    ('M10', 'sonstiges', 'S3', 'I2', 'verbrauch:cockpit_monat:vor=nach'): None,
    ('M10', 'speicher', 'S3', 'I2', 'entladung:cockpit_monat:vor=nach'): None,
    ('M10', 'speicher', 'S3', 'I2', 'ladung:cockpit_monat:vor=nach'): None,
    # HA-Bauform E4a-2: neue Form W2-E (Entweder-oder) — dieselbe „Soll unklar"-Lage SA vor dem Abschluss, gemessen
    # 06.10.2026 (Cockpit → Monat ohne HA im vergangenen Monat: nichts). Neu angelegt, keine bestehende Zeile geändert.
    ('W2-E', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('W2-E', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('W2-E', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('W2-E', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('W2-E', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('W2-E', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('W2-E', 'sonstiges', 'S3', 'I2', 'erzeugung:cockpit_monat:vor=nach'): None,
    # E4c (W2-E-KATALOG berichtigt): die Menge „verbrauch“ gibt es beim Erzeuger nicht mehr — ihr Haltewert entfällt.
}
