"""Haltewerte der „Soll unklar"-Sichten beider Abnahme-Matrizen (HA-Bauform E0, eingefroren 05.10.2026).

Eine „Soll unklar"-Sicht wird gemessen und gezeigt, aber nicht bewertet — die Regel legt ihr Soll nicht fest
(``test_pv_achse_matrix.SOLL_UNKLAR``; ``test_achsen_matrix._soll_unklar``: ``SOLL_UNKLAR_MENGE``, die
S3-Vor-Regel ``_U_SA_VOR`` und die Klima-Arbeitszahl). Damit der Umbau auf die HA-Bauform
(``~/.claude/plans/bauplan-ha-bauform-s1-s2.md`` §7, letzte Zeile) sie nicht **still** ändert, steht hier je
Sicht der gemessene Wert gegen HEAD ``263c9d12``; ``test_soll_unklar_haltewert`` in beiden Matrix-Dateien prüft
„gemessen == festgehalten" (``None`` = keine Angabe; Zahl gleich bis 1e-6) und, dass jede „Soll unklar"-Sicht
genau einen Haltewert hat.

**Kein Soll.** Ein Haltewert sagt nicht, dass der Wert richtig ist — die Fachentscheide folgen getrennt. Wer einen
Wert absichtlich ändert (Fachentscheid oder Umbau mit benanntem Zielwert), ändert ihn hier mit Verweis; fällt eine
Sicht aus „Soll unklar" heraus, fällt ihr Haltewert mit.

Erzeugt aus der Messung beider Matrizen (Berlin; ``TZ=UTC`` gemessen identisch), Bericht
``~/.claude/plans/opus-berichte/HA-BAUFORM-E0.md`` Punkt 4.
"""

from __future__ import annotations

from typing import Optional

#: ``(Form, Weg, Invariante, Sicht) → gemessener Wert`` — PV-Matrix, 116 Sichten (E0) + 99 Sichten ``bkw_hub:*``
#: (N-638, unten eigener Block) + 39 Sichten N-640 (letzter Block).
PV_HALTEWERTE: dict[tuple[str, str, str, str], Optional[float]] = {
    ('F01', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F01', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F01', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F01', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F02', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F02', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F02', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F02', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F03', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F03', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F03', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F03', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F04', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F04', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F04', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F04', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F05', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F05', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F05', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F05', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F06', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F06', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F06', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F06', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F07', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F07', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F07', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F07', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F08a', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F08a', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F08a', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F08a', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F08b', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F08b', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F08b', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F08b', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F09a-G', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F09a-G', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F09a-G', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F09a-G', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F09a-oG', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F09a-oG', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F09a-oG', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F09a-oG', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F09b-G', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F09b-G', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F09b-G', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F09b-G', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F09b-oG', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F09b-oG', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F09b-oG', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F09b-oG', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F09c-G', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F09c-G', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F09c-G', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F09c-G', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F09c-oG', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F09c-oG', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F09c-oG', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F09c-oG', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F10', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F10', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F10', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F10', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F11', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F11', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F11', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F11', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F12', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F12', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F12', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F12', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F13a', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F13a', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F13a', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F13a', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F13b', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F13b', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F13b', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F13b', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F14', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F14', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F14', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F14', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F15', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F15', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F15', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F15', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('F16', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('F16', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('F16', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('F16', 'S3', 'I6', 'vor:cockpit_monat'): None,
    # ── N-638 (07.10.2026, Entscheid Master Option b): Komponenten → Balkonkraftwerk → Verlauf, gemessen am Bau
    # BAU-N636-N638.md (Skript `haltewerte_bkw_hub.py`, `messe_form` + `bewerte`). Zwei Formklassen, deren Soll nicht
    # entschieden ist: BKW ohne eigenen Zähler (F01 · F04 · F05 · F12 · W2-L — keine eigene Monatszeile, Hub 0;
    # Beobachtungsliste 07.10.2026) und an Modul-Kinder abgetretenes BKW (F09* — Hub zeigt den Zähler 90 kWh, die
    # Monats-Fakten 0; Beobachtungsliste 04.10.2026). Kopf derselben Antwort: 0 / 0 / 0 bzw. 90,0 / 64,3 / 25,7 kWh.
    ('F01', 'S1', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('F01', 'S1', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('F01', 'S1', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('F01', 'S2', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('F01', 'S2', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('F01', 'S2', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('F01', 'S3', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('F01', 'S3', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('F01', 'S3', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('F04', 'S1', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('F04', 'S1', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('F04', 'S1', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('F04', 'S2', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('F04', 'S2', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('F04', 'S2', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('F04', 'S3', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('F04', 'S3', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('F04', 'S3', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('F05', 'S1', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('F05', 'S1', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('F05', 'S1', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('F05', 'S2', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('F05', 'S2', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('F05', 'S2', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('F05', 'S3', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('F05', 'S3', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('F05', 'S3', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('F09a-G', 'S1', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 25.7143,
    ('F09a-G', 'S1', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 90.0,
    ('F09a-G', 'S1', 'I4', 'bkw_hub:Balkon:juni_ev'): 64.2857,
    ('F09a-G', 'S2', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 25.7143,
    ('F09a-G', 'S2', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 90.0,
    ('F09a-G', 'S2', 'I4', 'bkw_hub:Balkon:juni_ev'): 64.2857,
    ('F09a-G', 'S3', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 25.7143,
    ('F09a-G', 'S3', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 90.0,
    ('F09a-G', 'S3', 'I4', 'bkw_hub:Balkon:juni_ev'): 64.2857,
    ('F09a-oG', 'S1', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 25.7143,
    ('F09a-oG', 'S1', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 90.0,
    ('F09a-oG', 'S1', 'I4', 'bkw_hub:Balkon:juni_ev'): 64.2857,
    ('F09a-oG', 'S2', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 25.7143,
    ('F09a-oG', 'S2', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 90.0,
    ('F09a-oG', 'S2', 'I4', 'bkw_hub:Balkon:juni_ev'): 64.2857,
    ('F09a-oG', 'S3', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 25.7143,
    ('F09a-oG', 'S3', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 90.0,
    ('F09a-oG', 'S3', 'I4', 'bkw_hub:Balkon:juni_ev'): 64.2857,
    ('F09b-G', 'S1', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 25.7143,
    ('F09b-G', 'S1', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 90.0,
    ('F09b-G', 'S1', 'I4', 'bkw_hub:Balkon:juni_ev'): 64.2857,
    ('F09b-G', 'S2', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 25.7143,
    ('F09b-G', 'S2', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 90.0,
    ('F09b-G', 'S2', 'I4', 'bkw_hub:Balkon:juni_ev'): 64.2857,
    ('F09b-G', 'S3', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 25.7143,
    ('F09b-G', 'S3', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 90.0,
    ('F09b-G', 'S3', 'I4', 'bkw_hub:Balkon:juni_ev'): 64.2857,
    ('F09b-oG', 'S1', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 25.7143,
    ('F09b-oG', 'S1', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 90.0,
    ('F09b-oG', 'S1', 'I4', 'bkw_hub:Balkon:juni_ev'): 64.2857,
    ('F09b-oG', 'S2', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 25.7143,
    ('F09b-oG', 'S2', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 90.0,
    ('F09b-oG', 'S2', 'I4', 'bkw_hub:Balkon:juni_ev'): 64.2857,
    ('F09b-oG', 'S3', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 25.7143,
    ('F09b-oG', 'S3', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 90.0,
    ('F09b-oG', 'S3', 'I4', 'bkw_hub:Balkon:juni_ev'): 64.2857,
    ('F09c-G', 'S1', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 25.7143,
    ('F09c-G', 'S1', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 90.0,
    ('F09c-G', 'S1', 'I4', 'bkw_hub:Balkon:juni_ev'): 64.2857,
    ('F09c-G', 'S2', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 25.7143,
    ('F09c-G', 'S2', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 90.0,
    ('F09c-G', 'S2', 'I4', 'bkw_hub:Balkon:juni_ev'): 64.2857,
    ('F09c-G', 'S3', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 25.7143,
    ('F09c-G', 'S3', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 90.0,
    ('F09c-G', 'S3', 'I4', 'bkw_hub:Balkon:juni_ev'): 64.2857,
    ('F09c-oG', 'S1', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 25.7143,
    ('F09c-oG', 'S1', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 90.0,
    ('F09c-oG', 'S1', 'I4', 'bkw_hub:Balkon:juni_ev'): 64.2857,
    ('F09c-oG', 'S2', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 25.7143,
    ('F09c-oG', 'S2', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 90.0,
    ('F09c-oG', 'S2', 'I4', 'bkw_hub:Balkon:juni_ev'): 64.2857,
    ('F09c-oG', 'S3', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 25.7143,
    ('F09c-oG', 'S3', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 90.0,
    ('F09c-oG', 'S3', 'I4', 'bkw_hub:Balkon:juni_ev'): 64.2857,
    ('F12', 'S1', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('F12', 'S1', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('F12', 'S1', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('F12', 'S2', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('F12', 'S2', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('F12', 'S2', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('F12', 'S3', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('F12', 'S3', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('F12', 'S3', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('W2-L', 'S1', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('W2-L', 'S1', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('W2-L', 'S1', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('W2-L', 'S2', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('W2-L', 'S2', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('W2-L', 'S2', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('W2-L', 'S3', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('W2-L', 'S3', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('W2-L', 'S3', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    # ── N-640 (Frank85, gemessen 08.10.2026 gegen HEAD 25ca0ec7, Bericht opus-berichte/BAU-N639-N640.md): die drei
    # Formen N640-1/-2/-3 — `bkw_hub:*` (BKW ohne Zähler, wie oben), S3 vor dem Abschluss (`_U_SA_VOR`) und die
    # Variante-1-Sichten sind seit dem Entscheid Master 08.10. bewertet (Soll 540), ohne Haltewert.
    ('N640-1', 'S1', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('N640-1', 'S1', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('N640-1', 'S1', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('N640-1', 'S2', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('N640-1', 'S2', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('N640-1', 'S2', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('N640-1', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('N640-1', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('N640-1', 'S3', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('N640-1', 'S3', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('N640-1', 'S3', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('N640-1', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('N640-1', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('N640-2', 'S1', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('N640-2', 'S1', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('N640-2', 'S1', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('N640-2', 'S2', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('N640-2', 'S2', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('N640-2', 'S2', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('N640-2', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('N640-2', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('N640-2', 'S3', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('N640-2', 'S3', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('N640-2', 'S3', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('N640-2', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('N640-2', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('N640-3', 'S1', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('N640-3', 'S1', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('N640-3', 'S1', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('N640-3', 'S2', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('N640-3', 'S2', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('N640-3', 'S2', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('N640-3', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('N640-3', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('N640-3', 'S3', 'I4', 'bkw_hub:Balkon:juni_einspeisung'): 0.0,
    ('N640-3', 'S3', 'I4', 'bkw_hub:Balkon:juni_erzeugung'): 0.0,
    ('N640-3', 'S3', 'I4', 'bkw_hub:Balkon:juni_ev'): 0.0,
    ('N640-3', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('N640-3', 'S3', 'I6', 'vor:cockpit_monat'): None,
    # N-588 (10.10.2026): die drei Formen des Messpunkt-Vertrags (W2-D, W2-B, W2-B7) unter der S3-Vor-Regel (`_U_SA_VOR`)
    # — gemessen gegen den Arbeitsbaum nach B1–B3. (Das CO₂ der ROI-Zeile stand hier bis B7, N-647, als Haltewert.)
    ('W2-D', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('W2-D', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('W2-D', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('W2-D', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('W2-B', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('W2-B', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('W2-B', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('W2-B', 'S3', 'I6', 'vor:cockpit_monat'): None,
    ('W2-B7', 'S3', 'I2', 'cockpit_monat:vor=nach'): None,
    ('W2-B7', 'S3', 'I3', 'cockpit_monat:vor'): None,
    ('W2-B7', 'S3', 'I5', 'cockpit_monat:vor'): None,
    ('W2-B7', 'S3', 'I6', 'vor:cockpit_monat'): None,
}

#: ``(Form, Größe, Weg, Invariante, Sicht) → gemessener Wert`` — Achsen-Matrix, 415 Sichten (E4d: +26); die 6 Sichten
#: Hub-Verlauf (letzter Block) sind mit N-645 entfallen.
ACHSEN_HALTEWERTE: dict[tuple[str, str, str, str, str], Optional[float]] = {
    ('M01', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M01', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M01', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M01', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M01', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M01', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M01', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M01', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M02', 'emob', 'S3', 'I2', 'heim_netz:cockpit_monat:vor=nach'): 0.0,
    ('M02', 'emob', 'S3', 'I2', 'heim_pv:cockpit_monat:vor=nach'): 0.0,
    ('M02', 'emob', 'S3', 'I2', 'heimladung:cockpit_monat:vor=nach'): None,
    ('M02', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M02', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M02', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M02', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M02', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M02', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M02', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M02', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M02', 'speicher', 'S3', 'I2', 'entladung:cockpit_monat:vor=nach'): None,
    ('M02', 'speicher', 'S3', 'I2', 'ladung:cockpit_monat:vor=nach'): None,
    ('M03', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M03', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M03', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M03', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M03', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M03', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M03', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M03', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M04', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M04', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M04', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M04', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M04', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M04', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M04', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M04', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M04', 'speicher', 'S3', 'I2', 'entladung:cockpit_monat:vor=nach'): None,
    ('M04', 'speicher', 'S3', 'I2', 'ladung:cockpit_monat:vor=nach'): None,
    ('M04', 'speicher', 'S3', 'I2', 'netzladung:cockpit_monat:vor=nach'): None,
    ('M05', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M05', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M05', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M05', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M05', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M05', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M05', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M05', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M05', 'wp', 'HA', 'I1', 'heizung:cockpit_jahr'): None,
    ('M05', 'wp', 'HA', 'I1', 'heizung:fakten_tw'): 0.0,
    ('M05', 'wp', 'HA', 'I1', 'heizung:jahr_verlauf'): 0.0,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'HA', 'I1', 'modus_heizen:cockpit_jahr'): 19.5,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'HA', 'I1', 'modus_heizen:fakten_tw'): 19.8,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'HA', 'I1', 'modus_warmwasser:cockpit_jahr'): 1.8,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'HA', 'I1', 'modus_warmwasser:fakten_tw'): 1.8,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'HA', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M05', 'wp', 'HA', 'I1', 'warmwasser:fakten_tw'): 0.0,
    ('M05', 'wp', 'HA', 'I1', 'warmwasser:jahr_verlauf'): 0.0,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'HA', 'I3', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'HA', 'I3', 'heizung:fakten_tw'): 0.0,
    ('M05', 'wp', 'HA', 'I3', 'modus_heizen:cockpit_monat'): 19.5,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'HA', 'I3', 'modus_heizen:fakten_tw'): 19.8,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'HA', 'I3', 'modus_warmwasser:cockpit_monat'): 1.8,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'HA', 'I3', 'modus_warmwasser:fakten_tw'): 1.8,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'HA', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'HA', 'I3', 'warmwasser:fakten_tw'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'heizung:cockpit_jahr'): None,
    ('M05', 'wp', 'S1', 'I1', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'S1', 'I1', 'heizung:community'): 648.0,
    ('M05', 'wp', 'S1', 'I1', 'heizung:pdf_kopf'): None,
    ('M05', 'wp', 'S1', 'I1', 'heizung:tabelle'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'heizung:uebersicht'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'heizung:zeitreihe'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'modus_heizen:cockpit_jahr'): 198.0,  # E4d: war 0.0 (H-1: Abschluss schreibt den Kanal-Split, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S1', 'I1', 'modus_heizen:cockpit_monat'): 198.0,  # E4d: war 0.0 (H-1: Abschluss schreibt den Kanal-Split, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S1', 'I1', 'modus_heizen:uebersicht'): 217.8,  # E4d: war 0.0 (Kanal-Leser; H-1: Abschluss schreibt den Kanal-Split, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S1', 'I1', 'modus_heizen:zeitreihe'): 198.0,  # E4d: war 0.0 (H-1: Abschluss schreibt den Kanal-Split, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S1', 'I1', 'modus_warmwasser:cockpit_jahr'): 18.0,  # E4d: war 0.0 (H-1: Abschluss schreibt den Kanal-Split, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S1', 'I1', 'modus_warmwasser:cockpit_monat'): 18.0,  # E4d: war 0.0 (H-1: Abschluss schreibt den Kanal-Split, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S1', 'I1', 'modus_warmwasser:uebersicht'): 19.8,  # E4d: war 0.0 (Kanal-Leser; H-1: Abschluss schreibt den Kanal-Split, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S1', 'I1', 'modus_warmwasser:zeitreihe'): 18.0,  # E4d: war 0.0 (H-1: Abschluss schreibt den Kanal-Split, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S1', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M05', 'wp', 'S1', 'I1', 'warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'S1', 'I1', 'warmwasser:community'): None,
    ('M05', 'wp', 'S1', 'I1', 'warmwasser:pdf_kopf'): None,
    ('M05', 'wp', 'S1', 'I1', 'warmwasser:tabelle'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'warmwasser:uebersicht'): 0.0,
    ('M05', 'wp', 'S1', 'I1', 'warmwasser:zeitreihe'): 0.0,
    ('M05', 'wp', 'S1', 'I2', 'heizung:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S1', 'I2', 'heizung:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S1', 'I2', 'heizung:jahr_verlauf:vor=nach'): 0.0,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S1', 'I2', 'modus_heizen:cockpit_monat:vor=nach'): 198.0,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S1', 'I2', 'modus_heizen:fakten:tageswert=gespeichert'): 198.0,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S1', 'I2', 'modus_warmwasser:cockpit_monat:vor=nach'): 18.0,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S1', 'I2', 'modus_warmwasser:fakten:tageswert=gespeichert'): 18.0,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S1', 'I2', 'warmwasser:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S1', 'I2', 'warmwasser:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S1', 'I2', 'warmwasser:jahr_verlauf:vor=nach'): 0.0,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S1', 'I3', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'S1', 'I3', 'heizung:fakten'): 0.0,
    ('M05', 'wp', 'S1', 'I3', 'modus_heizen:cockpit_monat'): 198.0,  # E4d: war 0.0 (H-1: Abschluss schreibt den Kanal-Split, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S1', 'I3', 'modus_heizen:fakten'): 198.0,  # E4d: war 0.0 (H-1: Abschluss schreibt den Kanal-Split, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S1', 'I3', 'modus_warmwasser:cockpit_monat'): 18.0,  # E4d: war 0.0 (H-1: Abschluss schreibt den Kanal-Split, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S1', 'I3', 'modus_warmwasser:fakten'): 18.0,  # E4d: war 0.0 (H-1: Abschluss schreibt den Kanal-Split, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S1', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'S1', 'I3', 'warmwasser:fakten'): 0.0,
    ('M05', 'wp', 'S1', 'I6', 'heizung:cockpit_jahr'): None,
    ('M05', 'wp', 'S1', 'I6', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'S1', 'I6', 'heizung:community'): 648.0,
    ('M05', 'wp', 'S1', 'I6', 'heizung:fakten'): 0.0,
    ('M05', 'wp', 'S1', 'I6', 'heizung:pdf_kopf'): None,
    ('M05', 'wp', 'S1', 'I6', 'heizung:tabelle'): 0.0,
    ('M05', 'wp', 'S1', 'I6', 'heizung:uebersicht'): 0.0,
    ('M05', 'wp', 'S1', 'I6', 'heizung:zeitreihe'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'heizung:cockpit_jahr'): None,
    ('M05', 'wp', 'S2', 'I1', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'S2', 'I1', 'heizung:community'): 648.0,
    ('M05', 'wp', 'S2', 'I1', 'heizung:pdf_kopf'): None,
    ('M05', 'wp', 'S2', 'I1', 'heizung:tabelle'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'heizung:uebersicht'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'heizung:zeitreihe'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'modus_heizen:cockpit_jahr'): 198.0,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S2', 'I1', 'modus_heizen:cockpit_monat'): 198.0,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S2', 'I1', 'modus_heizen:uebersicht'): 217.8,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S2', 'I1', 'modus_heizen:zeitreihe'): 198.0,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S2', 'I1', 'modus_warmwasser:cockpit_jahr'): 18.0,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S2', 'I1', 'modus_warmwasser:cockpit_monat'): 18.0,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S2', 'I1', 'modus_warmwasser:uebersicht'): 19.8,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S2', 'I1', 'modus_warmwasser:zeitreihe'): 18.0,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S2', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M05', 'wp', 'S2', 'I1', 'warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'S2', 'I1', 'warmwasser:community'): None,
    ('M05', 'wp', 'S2', 'I1', 'warmwasser:pdf_kopf'): None,
    ('M05', 'wp', 'S2', 'I1', 'warmwasser:tabelle'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'warmwasser:uebersicht'): 0.0,
    ('M05', 'wp', 'S2', 'I1', 'warmwasser:zeitreihe'): 0.0,
    ('M05', 'wp', 'S2', 'I2', 'heizung:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S2', 'I2', 'heizung:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S2', 'I2', 'heizung:jahr_verlauf:vor=nach'): 0.0,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S2', 'I2', 'modus_heizen:cockpit_monat:vor=nach'): 198.0,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S2', 'I2', 'modus_heizen:fakten:tageswert=gespeichert'): 198.0,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S2', 'I2', 'modus_warmwasser:cockpit_monat:vor=nach'): 18.0,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S2', 'I2', 'modus_warmwasser:fakten:tageswert=gespeichert'): 18.0,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S2', 'I2', 'warmwasser:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S2', 'I2', 'warmwasser:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S2', 'I2', 'warmwasser:jahr_verlauf:vor=nach'): 0.0,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S2', 'I3', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'S2', 'I3', 'heizung:fakten'): 0.0,
    ('M05', 'wp', 'S2', 'I3', 'modus_heizen:cockpit_monat'): 198.0,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S2', 'I3', 'modus_heizen:fakten'): 198.0,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S2', 'I3', 'modus_warmwasser:cockpit_monat'): 18.0,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S2', 'I3', 'modus_warmwasser:fakten'): 18.0,  # E4d: war 0.0 (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M05', 'wp', 'S2', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'S2', 'I3', 'warmwasser:fakten'): 0.0,
    ('M05', 'wp', 'S2', 'I6', 'heizung:cockpit_jahr'): None,
    ('M05', 'wp', 'S2', 'I6', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'S2', 'I6', 'heizung:community'): 648.0,
    ('M05', 'wp', 'S2', 'I6', 'heizung:fakten'): 0.0,
    ('M05', 'wp', 'S2', 'I6', 'heizung:pdf_kopf'): None,
    ('M05', 'wp', 'S2', 'I6', 'heizung:tabelle'): 0.0,
    ('M05', 'wp', 'S2', 'I6', 'heizung:uebersicht'): 0.0,
    ('M05', 'wp', 'S2', 'I6', 'heizung:zeitreihe'): 0.0,
    ('M05', 'wp', 'S3', 'I1', 'heizung:cockpit_jahr'): None,
    ('M05', 'wp', 'S3', 'I1', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'S3', 'I1', 'heizung:community'): 648.0,
    ('M05', 'wp', 'S3', 'I1', 'heizung:pdf_kopf'): None,
    ('M05', 'wp', 'S3', 'I1', 'heizung:tabelle'): 0.0,
    ('M05', 'wp', 'S3', 'I1', 'heizung:uebersicht'): 0.0,
    ('M05', 'wp', 'S3', 'I1', 'heizung:zeitreihe'): 0.0,
    ('M05', 'wp', 'S3', 'I1', 'modus_heizen:cockpit_jahr'): None,
    ('M05', 'wp', 'S3', 'I1', 'modus_heizen:cockpit_monat'): None,
    ('M05', 'wp', 'S3', 'I1', 'modus_heizen:uebersicht'): None,
    ('M05', 'wp', 'S3', 'I1', 'modus_heizen:zeitreihe'): None,
    ('M05', 'wp', 'S3', 'I1', 'modus_warmwasser:cockpit_jahr'): None,
    ('M05', 'wp', 'S3', 'I1', 'modus_warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'S3', 'I1', 'modus_warmwasser:uebersicht'): None,
    ('M05', 'wp', 'S3', 'I1', 'modus_warmwasser:zeitreihe'): None,
    ('M05', 'wp', 'S3', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M05', 'wp', 'S3', 'I1', 'warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'S3', 'I1', 'warmwasser:community'): None,
    ('M05', 'wp', 'S3', 'I1', 'warmwasser:pdf_kopf'): None,
    ('M05', 'wp', 'S3', 'I1', 'warmwasser:tabelle'): 0.0,
    ('M05', 'wp', 'S3', 'I1', 'warmwasser:uebersicht'): 0.0,
    ('M05', 'wp', 'S3', 'I1', 'warmwasser:zeitreihe'): 0.0,
    ('M05', 'wp', 'S3', 'I2', 'heizung:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S3', 'I2', 'heizung:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S3', 'I2', 'heizung:jahr_verlauf:vor=nach'): None,
    ('M05', 'wp', 'S3', 'I2', 'modus_heizen:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S3', 'I2', 'modus_heizen:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S3', 'I2', 'modus_warmwasser:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S3', 'I2', 'modus_warmwasser:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S3', 'I2', 'strom:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S3', 'I2', 'waerme:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S3', 'I2', 'warmwasser:cockpit_monat:vor=nach'): None,
    ('M05', 'wp', 'S3', 'I2', 'warmwasser:fakten:tageswert=gespeichert'): 0.0,
    ('M05', 'wp', 'S3', 'I2', 'warmwasser:jahr_verlauf:vor=nach'): None,
    ('M05', 'wp', 'S3', 'I3', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'S3', 'I3', 'heizung:fakten'): 0.0,
    ('M05', 'wp', 'S3', 'I3', 'modus_heizen:cockpit_monat'): None,
    ('M05', 'wp', 'S3', 'I3', 'modus_heizen:fakten'): 0.0,
    ('M05', 'wp', 'S3', 'I3', 'modus_warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'S3', 'I3', 'modus_warmwasser:fakten'): 0.0,
    ('M05', 'wp', 'S3', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'S3', 'I3', 'warmwasser:fakten'): 0.0,
    ('M05', 'wp', 'S3', 'I6', 'heizung:cockpit_jahr'): None,
    ('M05', 'wp', 'S3', 'I6', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'S3', 'I6', 'heizung:community'): 648.0,
    ('M05', 'wp', 'S3', 'I6', 'heizung:fakten'): 0.0,
    ('M05', 'wp', 'S3', 'I6', 'heizung:pdf_kopf'): None,
    ('M05', 'wp', 'S3', 'I6', 'heizung:tabelle'): 0.0,
    ('M05', 'wp', 'S3', 'I6', 'heizung:uebersicht'): 0.0,
    ('M05', 'wp', 'S3', 'I6', 'heizung:zeitreihe'): 0.0,
    ('M05', 'wp', 'SA', 'I1', 'heizung:cockpit_jahr'): None,
    ('M05', 'wp', 'SA', 'I1', 'heizung:fakten_tw'): 0.0,
    ('M05', 'wp', 'SA', 'I1', 'heizung:jahr_verlauf'): None,
    ('M05', 'wp', 'SA', 'I1', 'modus_heizen:cockpit_jahr'): None,
    ('M05', 'wp', 'SA', 'I1', 'modus_heizen:fakten_tw'): 0.0,
    ('M05', 'wp', 'SA', 'I1', 'modus_warmwasser:cockpit_jahr'): None,
    ('M05', 'wp', 'SA', 'I1', 'modus_warmwasser:fakten_tw'): 0.0,
    ('M05', 'wp', 'SA', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M05', 'wp', 'SA', 'I1', 'warmwasser:fakten_tw'): 0.0,
    ('M05', 'wp', 'SA', 'I1', 'warmwasser:jahr_verlauf'): None,
    ('M05', 'wp', 'SA', 'I3', 'heizung:cockpit_monat'): None,
    ('M05', 'wp', 'SA', 'I3', 'heizung:fakten_tw'): 0.0,
    ('M05', 'wp', 'SA', 'I3', 'modus_heizen:cockpit_monat'): None,
    ('M05', 'wp', 'SA', 'I3', 'modus_heizen:fakten_tw'): 0.0,
    ('M05', 'wp', 'SA', 'I3', 'modus_warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'SA', 'I3', 'modus_warmwasser:fakten_tw'): 0.0,
    ('M05', 'wp', 'SA', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M05', 'wp', 'SA', 'I3', 'warmwasser:fakten_tw'): 0.0,
    ('M06', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M06', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M06', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M06', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M06', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M06', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M06', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M06', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M06', 'wp', 'HA', 'I5', 'cockpit_monat:jaz:Klima'): 3.0,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M06', 'wp', 'S1', 'I5', 'cockpit_monat:jaz:Klima'): 3.0,
    ('M06', 'wp', 'S2', 'I5', 'cockpit_monat:jaz:Klima'): 3.0,
    ('M06', 'wp', 'S3', 'I2', 'heizung:cockpit_monat:vor=nach'): None,
    ('M06', 'wp', 'S3', 'I2', 'kaelte:cockpit_monat:vor=nach'): None,
    ('M06', 'wp', 'S3', 'I2', 'modus_heizen:cockpit_monat:vor=nach'): None,
    ('M06', 'wp', 'S3', 'I2', 'modus_kuehlen:cockpit_monat:vor=nach'): None,
    ('M06', 'wp', 'S3', 'I2', 'strom:cockpit_monat:vor=nach'): None,
    ('M06', 'wp', 'S3', 'I2', 'strom_heizen:cockpit_monat:vor=nach'): None,
    ('M06', 'wp', 'S3', 'I2', 'strom_warmwasser:cockpit_monat:vor=nach'): None,
    ('M06', 'wp', 'S3', 'I2', 'waerme:cockpit_monat:vor=nach'): None,
    ('M06', 'wp', 'S3', 'I2', 'warmwasser:cockpit_monat:vor=nach'): None,
    ('M06', 'wp', 'S3', 'I5', 'cockpit_monat:jaz:Klima'): 3.0,
    ('M06', 'wp', 'SA', 'I5', 'cockpit_monat:jaz:Klima'): None,
    ('M07', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M07', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M07', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M07', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M07', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M07', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M07', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M07', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M07', 'sonstiges', 'S3', 'I2', 'verbrauch:cockpit_monat:vor=nach'): None,
    ('M07', 'wp', 'HA', 'I1', 'heizung:cockpit_jahr'): None,
    ('M07', 'wp', 'HA', 'I1', 'heizung:fakten_tw'): 0.0,
    ('M07', 'wp', 'HA', 'I1', 'heizung:jahr_verlauf'): 0.0,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M07', 'wp', 'HA', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M07', 'wp', 'HA', 'I1', 'warmwasser:fakten_tw'): 0.0,
    ('M07', 'wp', 'HA', 'I1', 'warmwasser:jahr_verlauf'): 0.0,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M07', 'wp', 'HA', 'I3', 'heizung:cockpit_monat'): None,
    ('M07', 'wp', 'HA', 'I3', 'heizung:fakten_tw'): 0.0,
    ('M07', 'wp', 'HA', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M07', 'wp', 'HA', 'I3', 'warmwasser:fakten_tw'): 0.0,
    ('M07', 'wp', 'S1', 'I1', 'heizung:cockpit_jahr'): None,
    ('M07', 'wp', 'S1', 'I1', 'heizung:cockpit_monat'): None,
    ('M07', 'wp', 'S1', 'I1', 'heizung:community'): None,
    ('M07', 'wp', 'S1', 'I1', 'heizung:pdf_kopf'): None,
    ('M07', 'wp', 'S1', 'I1', 'heizung:tabelle'): 0.0,
    ('M07', 'wp', 'S1', 'I1', 'heizung:uebersicht'): 0.0,
    ('M07', 'wp', 'S1', 'I1', 'heizung:zeitreihe'): 0.0,
    ('M07', 'wp', 'S1', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M07', 'wp', 'S1', 'I1', 'warmwasser:cockpit_monat'): None,
    ('M07', 'wp', 'S1', 'I1', 'warmwasser:community'): None,
    ('M07', 'wp', 'S1', 'I1', 'warmwasser:pdf_kopf'): None,
    ('M07', 'wp', 'S1', 'I1', 'warmwasser:tabelle'): 0.0,
    ('M07', 'wp', 'S1', 'I1', 'warmwasser:uebersicht'): 0.0,
    ('M07', 'wp', 'S1', 'I1', 'warmwasser:zeitreihe'): 0.0,
    ('M07', 'wp', 'S1', 'I2', 'heizung:cockpit_monat:vor=nach'): None,
    ('M07', 'wp', 'S1', 'I2', 'heizung:fakten:tageswert=gespeichert'): 0.0,
    ('M07', 'wp', 'S1', 'I2', 'heizung:jahr_verlauf:vor=nach'): 0.0,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M07', 'wp', 'S1', 'I2', 'warmwasser:cockpit_monat:vor=nach'): None,
    ('M07', 'wp', 'S1', 'I2', 'warmwasser:fakten:tageswert=gespeichert'): 0.0,
    ('M07', 'wp', 'S1', 'I2', 'warmwasser:jahr_verlauf:vor=nach'): 0.0,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M07', 'wp', 'S1', 'I3', 'heizung:cockpit_monat'): None,
    ('M07', 'wp', 'S1', 'I3', 'heizung:fakten'): 0.0,
    ('M07', 'wp', 'S1', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M07', 'wp', 'S1', 'I3', 'warmwasser:fakten'): 0.0,
    ('M07', 'wp', 'S2', 'I1', 'heizung:cockpit_jahr'): None,
    ('M07', 'wp', 'S2', 'I1', 'heizung:cockpit_monat'): None,
    ('M07', 'wp', 'S2', 'I1', 'heizung:community'): None,
    ('M07', 'wp', 'S2', 'I1', 'heizung:pdf_kopf'): None,
    ('M07', 'wp', 'S2', 'I1', 'heizung:tabelle'): 0.0,
    ('M07', 'wp', 'S2', 'I1', 'heizung:uebersicht'): 0.0,
    ('M07', 'wp', 'S2', 'I1', 'heizung:zeitreihe'): 0.0,
    ('M07', 'wp', 'S2', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M07', 'wp', 'S2', 'I1', 'warmwasser:cockpit_monat'): None,
    ('M07', 'wp', 'S2', 'I1', 'warmwasser:community'): None,
    ('M07', 'wp', 'S2', 'I1', 'warmwasser:pdf_kopf'): None,
    ('M07', 'wp', 'S2', 'I1', 'warmwasser:tabelle'): 0.0,
    ('M07', 'wp', 'S2', 'I1', 'warmwasser:uebersicht'): 0.0,
    ('M07', 'wp', 'S2', 'I1', 'warmwasser:zeitreihe'): 0.0,
    ('M07', 'wp', 'S2', 'I2', 'heizung:cockpit_monat:vor=nach'): None,
    ('M07', 'wp', 'S2', 'I2', 'heizung:fakten:tageswert=gespeichert'): 0.0,
    ('M07', 'wp', 'S2', 'I2', 'heizung:jahr_verlauf:vor=nach'): 0.0,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M07', 'wp', 'S2', 'I2', 'warmwasser:cockpit_monat:vor=nach'): None,
    ('M07', 'wp', 'S2', 'I2', 'warmwasser:fakten:tageswert=gespeichert'): 0.0,
    ('M07', 'wp', 'S2', 'I2', 'warmwasser:jahr_verlauf:vor=nach'): 0.0,  # E4d: war None (Kanal-Leser, Bericht HA-BAUFORM-E4D)
    ('M07', 'wp', 'S2', 'I3', 'heizung:cockpit_monat'): None,
    ('M07', 'wp', 'S2', 'I3', 'heizung:fakten'): 0.0,
    ('M07', 'wp', 'S2', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M07', 'wp', 'S2', 'I3', 'warmwasser:fakten'): 0.0,
    ('M07', 'wp', 'S3', 'I1', 'heizung:cockpit_jahr'): None,
    ('M07', 'wp', 'S3', 'I1', 'heizung:cockpit_monat'): None,
    ('M07', 'wp', 'S3', 'I1', 'heizung:community'): None,
    ('M07', 'wp', 'S3', 'I1', 'heizung:pdf_kopf'): None,
    ('M07', 'wp', 'S3', 'I1', 'heizung:tabelle'): 0.0,
    ('M07', 'wp', 'S3', 'I1', 'heizung:uebersicht'): 0.0,
    ('M07', 'wp', 'S3', 'I1', 'heizung:zeitreihe'): 0.0,
    ('M07', 'wp', 'S3', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M07', 'wp', 'S3', 'I1', 'warmwasser:cockpit_monat'): None,
    ('M07', 'wp', 'S3', 'I1', 'warmwasser:community'): None,
    ('M07', 'wp', 'S3', 'I1', 'warmwasser:pdf_kopf'): None,
    ('M07', 'wp', 'S3', 'I1', 'warmwasser:tabelle'): 0.0,
    ('M07', 'wp', 'S3', 'I1', 'warmwasser:uebersicht'): 0.0,
    ('M07', 'wp', 'S3', 'I1', 'warmwasser:zeitreihe'): 0.0,
    ('M07', 'wp', 'S3', 'I2', 'heizung:cockpit_monat:vor=nach'): None,
    ('M07', 'wp', 'S3', 'I2', 'heizung:fakten:tageswert=gespeichert'): 0.0,
    ('M07', 'wp', 'S3', 'I2', 'heizung:jahr_verlauf:vor=nach'): None,
    ('M07', 'wp', 'S3', 'I2', 'strom:cockpit_monat:vor=nach'): None,
    ('M07', 'wp', 'S3', 'I2', 'waerme:cockpit_monat:vor=nach'): None,
    ('M07', 'wp', 'S3', 'I2', 'warmwasser:cockpit_monat:vor=nach'): None,
    ('M07', 'wp', 'S3', 'I2', 'warmwasser:fakten:tageswert=gespeichert'): 0.0,
    ('M07', 'wp', 'S3', 'I2', 'warmwasser:jahr_verlauf:vor=nach'): None,
    ('M07', 'wp', 'S3', 'I3', 'heizung:cockpit_monat'): None,
    ('M07', 'wp', 'S3', 'I3', 'heizung:fakten'): 0.0,
    ('M07', 'wp', 'S3', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M07', 'wp', 'S3', 'I3', 'warmwasser:fakten'): 0.0,
    ('M07', 'wp', 'SA', 'I1', 'heizung:cockpit_jahr'): None,
    ('M07', 'wp', 'SA', 'I1', 'heizung:fakten_tw'): 0.0,
    ('M07', 'wp', 'SA', 'I1', 'heizung:jahr_verlauf'): None,
    ('M07', 'wp', 'SA', 'I1', 'warmwasser:cockpit_jahr'): None,
    ('M07', 'wp', 'SA', 'I1', 'warmwasser:fakten_tw'): 0.0,
    ('M07', 'wp', 'SA', 'I1', 'warmwasser:jahr_verlauf'): None,
    ('M07', 'wp', 'SA', 'I3', 'heizung:cockpit_monat'): None,
    ('M07', 'wp', 'SA', 'I3', 'heizung:fakten_tw'): 0.0,
    ('M07', 'wp', 'SA', 'I3', 'warmwasser:cockpit_monat'): None,
    ('M07', 'wp', 'SA', 'I3', 'warmwasser:fakten_tw'): 0.0,
    ('M08', 'emob', 'S3', 'I2', 'heim_netz:cockpit_monat:vor=nach'): 0.0,
    ('M08', 'emob', 'S3', 'I2', 'heim_pv:cockpit_monat:vor=nach'): 90.0,
    ('M08', 'emob', 'S3', 'I2', 'heimladung:cockpit_monat:vor=nach'): None,
    ('M08', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M08', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M08', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M08', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M08', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M08', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M08', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M08', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M09', 'emob', 'S3', 'I2', 'heim_netz:cockpit_monat:vor=nach'): 0.0,
    ('M09', 'emob', 'S3', 'I2', 'heim_pv:cockpit_monat:vor=nach'): 0.0,
    ('M09', 'emob', 'S3', 'I2', 'heimladung:cockpit_monat:vor=nach'): None,
    ('M09', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M09', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M09', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M09', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M09', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M09', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M09', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M09', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M10', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('M10', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('M10', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('M10', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('M10', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('M10', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('M10', 'preis', 'S3', 'I2', 'kosten:cockpit_monat:vor=nach'): None,
    ('M10', 'preis', 'S3', 'I2', 'preis_effektiv:cockpit_monat:vor=nach'): 30.0,
    ('M10', 'sonstiges', 'S3', 'I2', 'erzeugung:cockpit_monat:vor=nach'): None,
    ('M10', 'sonstiges', 'S3', 'I2', 'verbrauch:cockpit_monat:vor=nach'): None,
    ('M10', 'speicher', 'S3', 'I2', 'entladung:cockpit_monat:vor=nach'): None,
    ('M10', 'speicher', 'S3', 'I2', 'ladung:cockpit_monat:vor=nach'): None,
    # HA-Bauform E4a-2: neue Form W2-E (Entweder-oder) — dieselbe „Soll unklar"-Lage SA vor dem Abschluss, gemessen
    # 06.10.2026 (Cockpit → Monat ohne HA im vergangenen Monat: nichts). Neu angelegt, keine bestehende Zeile geändert.
    ('W2-E', 'netz', 'S3', 'I2', 'autarkie:cockpit_monat:vor=nach'): None,
    ('W2-E', 'netz', 'S3', 'I2', 'eigenverbrauch:cockpit_monat:vor=nach'): None,
    ('W2-E', 'netz', 'S3', 'I2', 'einspeisung:cockpit_monat:vor=nach'): None,
    ('W2-E', 'netz', 'S3', 'I2', 'gesamtverbrauch:cockpit_monat:vor=nach'): None,
    ('W2-E', 'netz', 'S3', 'I2', 'netzbezug:cockpit_monat:vor=nach'): None,
    ('W2-E', 'netz', 'S3', 'I2', 'pv:cockpit_monat:vor=nach'): None,
    ('W2-E', 'sonstiges', 'S3', 'I2', 'erzeugung:cockpit_monat:vor=nach'): None,
    # E4c (W2-E-KATALOG berichtigt): die Menge „verbrauch“ gibt es beim Erzeuger nicht mehr — ihr Haltewert entfällt.
    # HA-Bauform E4d: neue „Soll unklar"-Sichten (W1, M05: der Strom je Betriebsart kommt ohne Abschluss aus dem
    # abgeleiteten Kanal und ist > 0 — I6 „nichts verschwindet" misst ihn jetzt). Bericht HA-BAUFORM-E4D.
    ('M05', 'wp', 'HA', 'I6', 'modus_heizen:cockpit_jahr'): 19.5,
    ('M05', 'wp', 'HA', 'I6', 'modus_heizen:cockpit_monat'): 19.5,
    ('M05', 'wp', 'HA', 'I6', 'modus_heizen:fakten_tw'): 19.8,
    ('M05', 'wp', 'HA', 'I6', 'modus_warmwasser:cockpit_jahr'): 1.8,
    ('M05', 'wp', 'HA', 'I6', 'modus_warmwasser:cockpit_monat'): 1.8,
    ('M05', 'wp', 'HA', 'I6', 'modus_warmwasser:fakten_tw'): 1.8,
    ('M05', 'wp', 'S1', 'I6', 'modus_heizen:cockpit_jahr'): 198.0,
    ('M05', 'wp', 'S1', 'I6', 'modus_heizen:cockpit_monat'): 198.0,
    ('M05', 'wp', 'S1', 'I6', 'modus_heizen:fakten'): 198.0,
    ('M05', 'wp', 'S1', 'I6', 'modus_heizen:uebersicht'): 217.8,
    ('M05', 'wp', 'S1', 'I6', 'modus_heizen:zeitreihe'): 198.0,
    ('M05', 'wp', 'S1', 'I6', 'modus_warmwasser:cockpit_jahr'): 18.0,
    ('M05', 'wp', 'S1', 'I6', 'modus_warmwasser:cockpit_monat'): 18.0,
    ('M05', 'wp', 'S1', 'I6', 'modus_warmwasser:fakten'): 18.0,
    ('M05', 'wp', 'S1', 'I6', 'modus_warmwasser:uebersicht'): 19.8,
    ('M05', 'wp', 'S1', 'I6', 'modus_warmwasser:zeitreihe'): 18.0,
    ('M05', 'wp', 'S2', 'I6', 'modus_heizen:cockpit_jahr'): 198.0,
    ('M05', 'wp', 'S2', 'I6', 'modus_heizen:cockpit_monat'): 198.0,
    ('M05', 'wp', 'S2', 'I6', 'modus_heizen:fakten'): 198.0,
    ('M05', 'wp', 'S2', 'I6', 'modus_heizen:uebersicht'): 217.8,
    ('M05', 'wp', 'S2', 'I6', 'modus_heizen:zeitreihe'): 198.0,
    ('M05', 'wp', 'S2', 'I6', 'modus_warmwasser:cockpit_jahr'): 18.0,
    ('M05', 'wp', 'S2', 'I6', 'modus_warmwasser:cockpit_monat'): 18.0,
    ('M05', 'wp', 'S2', 'I6', 'modus_warmwasser:fakten'): 18.0,
    ('M05', 'wp', 'S2', 'I6', 'modus_warmwasser:uebersicht'): 19.8,
    ('M05', 'wp', 'S2', 'I6', 'modus_warmwasser:zeitreihe'): 18.0,
    # Sicht „Hub-Verlauf": die sechs Haltewerte `verbrauch_verlauf:Σreihe=kopf` (M07 Pool, M10 Sauna; 0,0 gegen Kopf
    # 72 / 24) sind mit N-645 entfallen — Fachentscheid Master 09.10.2026, Soll „Verlauf = Kopf" (Segment „nicht
    # aufgeteilt"); die Sichten sind seither bewertet und grün.
}
